version: 2

release:
  mode: replace

builds:
  - id: trc
    main: .
    binary: trc
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - trc
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: trc
    homepage: https://github.com/mickamy/trc
    description: A local request tracer for Docker microservices.
    install: |
      bin.install "trc"
    repository:
      owner: mickamy
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

dockers:
  - id: trcd-amd64
    ids: []
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/mickamy/trcd:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: trcd-arm64
    ids: []
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/mickamy/trcd:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/mickamy/trcd:{{ .Version }}"
    image_templates:
      - "ghcr.io/mickamy/trcd:{{ .Version }}-amd64"
      - "ghcr.io/mickamy/trcd:{{ .Version }}-arm64"
  - name_template: "ghcr.io/mickamy/trcd:latest"
    image_templates:
      - "ghcr.io/mickamy/trcd:{{ .Version }}-amd64"
      - "ghcr.io/mickamy/trcd:{{ .Version }}-arm64"

changelog: {}
